In [1]:
import pandas as pd 
import numpy as np

In [2]:
import time
from datetime import datetime, date, time, timedelta
import dateutil.relativedelta

In [3]:
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
df=pd.read_excel('daily_offers.xlsx',parse_dates=['item_date'])

In [6]:
df.head()

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,20210401.0,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,20210401.0,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,0000000000000000000000000000000000104991,1668701718,20210401.0,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,20210401.0,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,20210101.0,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,20210401.0,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,20210401.0,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00

In [7]:
df.drop([52], axis=0, inplace=True)

In [17]:
df1=df.dropna( axis=0, how='any')

In [18]:
df1['item_date'] = pd.to_datetime(df1['item_date'], format='%Y%m%d',dayfirst=True)

In [19]:
df1

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,2021-04-01,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,2021-04-01,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,0000000000000000000000000000000000104991,1668701718,20210401.0,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,2021-04-01,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,20210101.0,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,2021-04-01,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,2021-04-01,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
181668,DE633116-D1DF-4846-982E-55EFC3658A76,2020-07-02,102.482422,30200854.0,25.0,Won,W,41.0,0.96,1220.0,0000000000000000000000000000000001000777,164141591,20200701.0,591.00
181669,A48374B1-E6DB-45F2-889A-1F9C27C099EB,2020-07-02,208.086469,30200854.0,25.0,Won,W,41.0,0.95,1500.0,0000000000000000000000000000000001000227,164141591,20200701.0,589.00
181670,91643238-5C7B-4237-9A5F-63AE3D35F320,2020-07-02,4.235594,30200854.0,25.0,Won,W,41.0,0.71,1250.0,0000000000000000000000000000000001004216,164141591,20200701.0,619.00
181671,7AFFD323-01D9-4E15-B80D-7D1B03498FC8,2020-07-02,-2000,30200854.0,25.0,Won,W,41.0,0.85,1250.0,0000000000000000000000000000000001001149,164141591,20200701.0,601.00
181672,AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC,2020-07-02,406.686538,30200854.0,25.0,Won,W,41.0,0.71,1240.0,0000000000000000000000000000000001005439,164141591,20200701.0,607.00

In [20]:
df1.isnull().sum()

id               0
item_date        0
quantity tons    0
customer         0
country          0
status           0
item type        0
application      0
thickness        0
width            0
material_ref     0
product_ref      0
delivery date    0
selling_price    0
dtype: int64

In [21]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103749 entries, 0 to 181672
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             103749 non-null  object
 1   item_date      103749 non-null  datetime64[ns]
 2   quantity tons  103749 non-null  object
 3   customer       103749 non-null  float64
 4   country        103749 non-null  float64
 5   status         103749 non-null  object
 6   item type      103749 non-null  object
 7   application    103749 non-null  float64
 8   thickness      103749 non-null  float64
 9   width          103749 non-null  float64
 10  material_ref   103749 non-null  object
 11  product_ref    103749 non-null  int64
 12  delivery date  103749 non-null  float64
 13  selling_price  103749 non-null  float64
dtypes: datetime64[ns](1), float64(7), int64(1), object(5)
memory usage: 11.9+ MB

In [22]:
df.describe()

,item_date,customer,country,application,thickness,width,product_ref,delivery date,selling_price
count,1.816710e+05,1.816710e+05,181644.000000,181648.000000,181671.000000,181672.000000,1.816720e+05,1.816710e+05,1.816710e+05
mean,2.020459e+07,3.051221e+07,44.892845,25.615928,2.564836,1295.286698,4.739696e+08,2.020738e+07,1.918040e+03
std,4.511765e+03,2.433388e+07,24.404165,17.754151,6.572338,261.632474,7.175117e+08,2.411065e+04,3.317966e+05
min,2.019192e+07,1.245800e+04,25.000000,2.000000,0.180000,1.000000,6.117280e+05,2.019040e+07,-1.160000e+03
25%,2.020093e+07,3.019688e+07,26.000000,10.000000,0.700000,1180.000000,6.119930e+05,2.020110e+07,6.690000e+02
50%,2.020113e+07,3.020524e+07,30.000000,15.000000,1.500000,1250.000000,6.406650e+05,2.021010e+07,8.120000e+02
75%,2.021020e+07,3.028042e+07,78.000000,41.000000,3.000000,1500.000000,1.332077e+09,2.021040e+07,9.530000e+02
max,2.021040e+07,2.147484e+09,113.000000,99.000000,2500.000000,2990.000000,1.722208e+09,3.031010e+07,1.000010e+08

In [23]:
df.head()

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,20210401.0,54.151139,30156308.0,28.0,Won,W,10.0,2.00,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,20210401.0,768.024839,30202938.0,25.0,Won,W,41.0,0.80,1210.0,0000000000000000000000000000000000104991,1668701718,20210401.0,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,20210401.0,386.127949,30153963.0,30.0,Won,WI,28.0,0.38,952.0,S0380700,628377,20210101.0,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,20210401.0,202.411065,30349574.0,32.0,Won,S,59.0,2.30,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,20210401.0,785.526262,30211560.0,28.0,Won,W,10.0,4.00,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00

In [ ]:
df3.head()

In [ ]:
df3['product_ref'].hist()

In [ ]:
df3['customer'].hist()

In [ ]:
df3.hist(column='item_date',by='status',layout=(12,16),figsize=(300,300),sharex=True)

In [ ]:
X = df1["delivery_date"]
Y = df1["selling_price"]
plt.scatter(X, Y)
plt.title("Scatter Plot")
plt.xlabel("delivery_date")
plt.ylabel("selling_price")
plt.show()

In [24]:
df1['quantity tons'] = df1['quantity tons'].astype(float)

In [25]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103749 entries, 0 to 181672
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             103749 non-null  object
 1   item_date      103749 non-null  datetime64[ns]
 2   quantity tons  103749 non-null  float64
 3   customer       103749 non-null  float64
 4   country        103749 non-null  float64
 5   status         103749 non-null  object
 6   item type      103749 non-null  object
 7   application    103749 non-null  float64
 8   thickness      103749 non-null  float64
 9   width          103749 non-null  float64
 10  material_ref   103749 non-null  object
 11  product_ref    103749 non-null  int64
 12  delivery date  103749 non-null  float64
 13  selling_price  103749 non-null  float64
dtypes: datetime64[ns](1), float64(8), int64(1), object(4)
memory usage: 11.9+ MB

In [26]:
df1['customer'] = df1['customer'].astype(int)

In [27]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103749 entries, 0 to 181672
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             103749 non-null  object
 1   item_date      103749 non-null  datetime64[ns]
 2   quantity tons  103749 non-null  float64
 3   customer       103749 non-null  int32
 4   country        103749 non-null  float64
 5   status         103749 non-null  object
 6   item type      103749 non-null  object
 7   application    103749 non-null  float64
 8   thickness      103749 non-null  float64
 9   width          103749 non-null  float64
 10  material_ref   103749 non-null  object
 11  product_ref    103749 non-null  int64
 12  delivery date  103749 non-null  float64
 13  selling_price  103749 non-null  float64
dtypes: datetime64[ns](1), float64(7), int32(1), int64(1), object(4)
memory usage: 11.5+ MB

In [28]:
df1.head(60)

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,2021-04-01,54.151139,30156308,28.0,Won,W,10.0,2.000,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,2021-04-01,768.024839,30202938,25.0,Won,W,41.0,0.800,1210.0,0000000000000000000000000000000000104991,1668701718,20210401.0,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,2021-04-01,386.127949,30153963,30.0,Won,WI,28.0,0.380,952.0,S0380700,628377,20210101.0,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,2021-04-01,202.411065,30349574,32.0,Won,S,59.0,2.300,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,2021-04-01,785.526262,30211560,28.0,Won,W,10.0,4.000,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00
5,FE372230-29B1-4A29-BB73-CB9D3078C286,2021-04-01,225.790676,30202938,25.0,Won,W,41.0,1.500,1265.0,0000000000000000000000000000000000102325,1668701718,20210401.0,983.00
6,E1B47219-42C8-411D-AE46-AD5256DC4757,2021-04-01,3.522613,30209509,30.0,Draft,W,41.0,0.380,1125.0,NBW_L+_A_1125_0.4,611993,20210701.0,18.00
7,AA3F18A2-A7D6-43DE-8644-F0632AE2CB68,2021-04-01,113.387124,30342192,32.0,Won,W,41.0,0.680,1220.0,0000000000000000000000000000000001000944,611993,20210101.0,931.00
8,2851F48B-DA32-4DF3-884B-17A3100DD65A,2021-04-01,69.071853,30341428,38.0,Won,S,10.0,0.600,1275.0,0000000000000000000000000000000000106786,1668701376,20210701.0,1363.00
9,6E4D638C-A820-4A40-836F-C9D48BC65528,2021-04-01,630.626917,30202938,25.0,Won,W,41.0,1.500,1165.0,0000000000000000000000000000000000102325,1668701718,20210401.0,983.00
10,B85870F5-E1C7-4CAA-A7DA-355DC192B11D,2021-04-01,9.175770,30209509,30.0,Draft,W,41.0,0.380,1125.0,NBW_L+_1125_0.4,611993,20210701.0,17.00
11,CA076845-2EDE-4C02-95BE-6C7B842026E8,2021-04-01,113.995666,30342192,32.0,Won,W,41.0,0.550,1220.0,0000000000000000000000000000000001000063,611993,20210101.0,954.00
13,E7039921-5DE1-4FD1-93A3-C25F9C389B82,2021-04-01,32.235317,30202362,27.0,Won,S,10.0,0.600,1010.0,DC04EK,628377,20210701.0,973.00
15,6B864D16-1C11-40D3-B4E3-917B68946F32,2021-04-01,35.310332,30329143,32.0,Won,S,41.0,0.370,1056.0,0000000000000000000000000000000001002867,611993,20210101.0,1028.00
16,A0E5D67D-A2E9-4401-B95E-277B562A4923,2021-04-01,75.124394,30153510,30.0,Won,W,41.0,0.595,1265.0,PEA1265X595SP,611993,20210401.0,1161.86
17,E1693AB6-73EB-4F3F-81E8-F5E4DF0C70B7,2021-04-01,20.807114,30211222,30.0,Won,W,10.0,0.450,900.0,684Z WHITE ETEX B7032,611993,20210701.0,1315.19
19,16253654-FBDA-4252-886C-55F8ACF2B08C,2021-04-01,53.581034,30329143,32.0,Won,S,41.0,0.550,1220.0,0000000000000000000000000000000001000113,611993,20210101.0,1002.00
20,F59B65F0-27F8-4BF2-BD25-EBA2B90869E5,2021-04-01,71.366978,30153510,30.0,Won,W,41.0,0.595,1265.0,GRE1265X595SP,611993,20210401.0,1161.31
21,A928C0FA-2F58-4322-A706-C4F30EDAE0F9,2021-04-01,471.838180,30202938,25.0,Won,W,41.0,2.500,1275.0,0000000000000000000000000000000000105003,1668701718,20210401.0,979.00
23,C2D456FC-A66A-4D95-BA1D-3CCEFF49DC2D,2021-04-01,53.729746,30329143,32.0,Won,S,41.0,0.550,1220.0,0000000000000000000000000000000001000063,611993,20210101.0,961.00
24,03AEAB77-279A-4137-B7E8-F223A56F65B2,2021-04-01,79.333990,30153510,30.0,Won,W,41.0,0.595,1265.0,BAS1265X595SP,611993,20210401.0,1155.09
25,0FE5567D-C4FC-4A9E-83DF-AC1E74917C17,2021-04-01,179.582796,30202938,25.0,Won,W,41.0,1.500,1025.0,0000000000000000000000000000000000102048,1670798778,20210401.0,917.00
27,D1B675A1-2CCB-4AE0-8507-F6904350FFFB,2021-04-01,927.430747,30152417,78.0,Won,S,28.0,1.040,912.0,1040912.O.TR.NPAC,628377,20210401.0,873.58
28,BEC18863-E965-478B-9861-A49A77F26655,2021-04-01,99.059199,30153510,30.0,Won,W,41.0,0.595,1207.0,GOO1208X595SP,611993,20210401.0,-1160.00
29,4D3B7D3D-AC31-42D1-95C6-D4D29D9694E9,2021-04-01,185.149656,30202938,25.0,Won,W,41.0,4.000,1500.0,0000000000000000000000000000000000102062,1670798778,20210401.0,874.00
31,194764F9-AE24-4EAF-9E7A-6505E9DE837F,2021-04-01,102.421773,30152417,78.0,Won,S,28.0,1.040,1132.0,1041132.O.TR.NPAC,628377,20210401.0,871.58
32,DEC4FAC8-7495-4897-95FA-ACD9878B5F5B,2021-04-01,75.757663,30153510,30.0,Won,W,41.0,0.595,1207.0,SNG1208X595SP,611993,20210401.0,1162.09
33,0925B8E9-FAB0-4598-8B06-01091320527B,2021-04-01,179.724514,30202938,25.0,Won,W,41.0,3.000,1445.0,0000000000000000000000000000000000102058,1670798778,20210401.0,870.00
35,555C35EF-AD81-47D4-8FBF-A61E584777CA,2021-04-01,207.776707,30152417,78.0,Won,S,28.0,1.040,1175.0,1041175.O.TR.NPAC,628377,20210401.0,866.58
37,D13B6F63-BFB7-4480-BD33-002F25CA6E44,2021-04-01,92.717256,30202938,25.0,Won,W,41.0,5.000,1465.0,0000000000000000000000000000000000101971,1670798778,20210401.0,838.00
39,423CFB04-6802-47BC-B2DF-D281A7651965,2021-04-01,44.772857,30152417,78.0,Won,S,28.0,1.040,966.0,104966.O.TR.NPAC,628377,20210401.0,872.58
40,34C78DC6-95A1-4B72-A657-06659568F3A0,2021-04-01,52.657880,30162161,77.0,Won,S,4.0,0.800,1300.0,DX51D+Z100 MA,164141591,20210601.0,1074.00
41,77AE96A1-0FD6-4974-934D-2FA53C502087,2021-04-01,59.907355,30202938,25.0,Won,W,41.0,2500.000,1260.0,0000000000000000000000000000000000101952,1670798778,20210401.0,0.00
43,5B033432-1C26-4383-9A2A-A016A39DA361,2021-04-01,540.754911,30152417,78.0,Won,S,28.0,0.450,900.0,045900.UO.TR.PAC,628377,20210401.0,903.58
44,DEC0A25C-21B5-49DC-942D-35DAB4782420,2021-04-01,56.831353,30162161,77.0,Won,S,4.0,1.100,1300.0,DX51D+Z100 MA,164141591,20210601.0,1048.00
45,508235B6-014A-4A0B-9C5E-EDD14DEA578D,2021-04-01,49.704555,30198267,25.0,Won,W,10.0,0.720,1208.0,45092827238F40SID,611993,20210701.0,1336.00
47,BA2952C9-8602-41AB-A987-0B5D7FE58A7A,2021-04-01,181.910842,30152417,78.0,Won,S,28.0,1.250,1022.0,12501022.O.TR.NPAC,628377,20210401.0,846.58
48,F4A7B46E-D56B-4528-AB71-17079E10E413,2021-04-01,26.533716,30162161,77.0,Won,S,4.0,0.800,1300.0,DX51D+Z100 MA,164141591,20210601.0,1065.00
49,71EA57F7-EEEB-4B70-8AD2-86A6BEB1190B,2021-04-01,132.884114,30336279,78.0,Won,S,59.0,1.800,900.0,DD11_CAT A,640665,20210501.0,852.00
51,2DEA4EB1-3129-437D-9F0B-663ECB4ED4FD,2021-04-01,126.776201,30152417,78.0,Won,S,28.0,1.260,1234.0,12601234.O.TR.NPAC,628377,20210401.0,842.58
53,D95278F5-203E-4554-8F07-E22F462DFD37,2021-04-01,30.899950,30336279,78.0,Won,S,59.0,3.000,800.0,S235JR+AR_CL1,640665,20210501.0,846.00
55,C9F0DF31-55AC-429D-9DB8-003ED24D9AC4,2021-04-01,371.655712,30152417,78.0,Won,S,28.0,0.450,1170.0,0451170.UO.TR.PAC SMALL CW,628377,20210401.0,887.58
56,F2E58F16-1BA2-4A41-B580-1C72059C811D,2021-04-01,62.574892,30268369,28.0,Won,W,38.0,0.550,1005.0,1PR1B1005055N2FBG1,611993,20210801.0,1375.00
57,78123D91-E068-47E0-ACE6-C21C69ADF2C4,2021-04-01,37.877146,30336279,78.0,Won,S,59.0,3.000,900.0,S235JR+AR_CL1,640665,20210501.0,840.00
59,3155F91C-A771-42EE-9322-DB0548B753B3,2021-04-01,204.258952,30152417,78.0,Won,S,28.0,1.040,1222.0,1041222 HC260LA NOPACK,628377,20210401.0,864.58
61,6716CC4F-183C-4048-9DF6-C6000FFECE82,2021-04-01,425.026183,30336279,78.0,Won,S,59.0,2.500,900.0,DD11_CAT A,640665,20210501.0,835.00
63,FD3B08F2-81EE-4FA2-AF1C-917F47B6B3D4,2021-04-01,901.304624,30152417,78.0,Won,S,28.0,0.450,1180.0,0451180.UO.NTR.PAC SMALL CW,628377,20210401.0,891.58
65,C8E38ACC-50EE-4304-8A68-B60A77EE126E,2021-04-01,835.337849,30336279,78.0,Won,S,59.0,3.000,900.0,DD11_CAT A,640665,20210501.0,832.00
67,7E2ABE04-E5F2-4272-96AC-EB54441F9FD4,2021-04-01,122.941681,30152417,78.0,Won,S,28.0,0.450,1160.0,0451160.UO.NTR.PAC SMALL CW,628377,20210401.0,894.58
69,72F6120C-363F-4DF4-81E0-8958FE7A4D92,2021-04-01,97.392554,30336279,78.0,Won,S,59.0,4.000,900.0,DD11_CAT A,640665,20210501.0,827.00
71,2215AB80-5392-408B-9908-2BE32BE11968,2021-04-01,129.226638,30152417,78.0,Won,S,28.0,1.250,1134.0,12501134.O.TR.NPAC,628377,20210401.0,845.58
73,B5ADF32D-0521-4188-813D-6A0188B75BDE,2021-04-01,89.967305,30336279,78.0,Won,S,59.0,2.000,900.0,DD11_CAT A,640665,20210501.0,837.00
75,D8F9609E-EBA1-4D2E-AEB5-EBF6E1BCFF62,2021-04-01,141.648185,30152417,78.0,Won,S,28.0,0.450,900.0,045900.UO.TR.PAC,628377,20210401.0,901.58
77,93D0E5CC-91FF-49E5-AE34-E70C0FB153E9,2021-04-01,58.370925,30156308,28.0,Won,S,10.0,0.600,915.0,FRS1 DC01,628377,20210701.0,927.00
81,55A5E0A7-AE58-49F9-9935-60A7F20D005F,2021-04-01,73.838363,30202938,25.0,Won,W,41.0,1.000,1320.0,0000000000000000000000000000000000101724,164141591,20210401.0,960.00
85,B13D3862-34D1-405B-9019-3D7345ABEDC2,2021-04-01,105.083220,30202938,25.0,Won,W,41.0,1.000,1225.0,0000000000000000000000000000000000104020,164141591,20210401.0,983.00
87,BC24869F-1325-440B-96F9-FEE618B15FC7,2021-04-01,27.219386,30349574,32.0,Won,S,59.0,1.300,1389.0,HC340LA-AM 0.93X1242,628377,20210701.0,942.00
89,B75D2D85-A077-4CB5-A587-311718ED30E1,2021-04-01,42.269970,30202938,25.0,Won,W,41.0,2.000,1444.0,0000000000000000000000000000000000101833,164141591,20210401.0,951.00
91,168858E8-086F-422F-96D6-F2CC4BD59C0E,2021-04-01,55.054828,30197978,28.0,Won,W,10.0,0.800,1250.0,DC01+ZV,1332077137,20210801.0,972.00
93,63ADC382-A952-4E57-B06B-C2E66BD27A09,2021-04-01,33.508328,30394817,78.0,Won,S,10.0,13.000,1640.0,04010128466FI7KRA,640665,20210601.0,829.00

In [29]:
df1['country'] = df1['country'].astype(int)

In [30]:
df1.head(20)

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,material_ref,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,2021-04-01,54.151139,30156308,28,Won,W,10.0,2.000,1500.0,DEQ1 S460MC,1670798778,20210701.0,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,2021-04-01,768.024839,30202938,25,Won,W,41.0,0.800,1210.0,0000000000000000000000000000000000104991,1668701718,20210401.0,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,2021-04-01,386.127949,30153963,30,Won,WI,28.0,0.380,952.0,S0380700,628377,20210101.0,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,2021-04-01,202.411065,30349574,32,Won,S,59.0,2.300,1317.0,DX51D+ZM310MAO 2.3X1317,1668701718,20210101.0,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,2021-04-01,785.526262,30211560,28,Won,W,10.0,4.000,2000.0,2_S275JR+AR-CL1,640665,20210301.0,577.00
5,FE372230-29B1-4A29-BB73-CB9D3078C286,2021-04-01,225.790676,30202938,25,Won,W,41.0,1.500,1265.0,0000000000000000000000000000000000102325,1668701718,20210401.0,983.00
6,E1B47219-42C8-411D-AE46-AD5256DC4757,2021-04-01,3.522613,30209509,30,Draft,W,41.0,0.380,1125.0,NBW_L+_A_1125_0.4,611993,20210701.0,18.00
7,AA3F18A2-A7D6-43DE-8644-F0632AE2CB68,2021-04-01,113.387124,30342192,32,Won,W,41.0,0.680,1220.0,0000000000000000000000000000000001000944,611993,20210101.0,931.00
8,2851F48B-DA32-4DF3-884B-17A3100DD65A,2021-04-01,69.071853,30341428,38,Won,S,10.0,0.600,1275.0,0000000000000000000000000000000000106786,1668701376,20210701.0,1363.00
9,6E4D638C-A820-4A40-836F-C9D48BC65528,2021-04-01,630.626917,30202938,25,Won,W,41.0,1.500,1165.0,0000000000000000000000000000000000102325,1668701718,20210401.0,983.00
10,B85870F5-E1C7-4CAA-A7DA-355DC192B11D,2021-04-01,9.175770,30209509,30,Draft,W,41.0,0.380,1125.0,NBW_L+_1125_0.4,611993,20210701.0,17.00
11,CA076845-2EDE-4C02-95BE-6C7B842026E8,2021-04-01,113.995666,30342192,32,Won,W,41.0,0.550,1220.0,0000000000000000000000000000000001000063,611993,20210101.0,954.00
13,E7039921-5DE1-4FD1-93A3-C25F9C389B82,2021-04-01,32.235317,30202362,27,Won,S,10.0,0.600,1010.0,DC04EK,628377,20210701.0,973.00
15,6B864D16-1C11-40D3-B4E3-917B68946F32,2021-04-01,35.310332,30329143,32,Won,S,41.0,0.370,1056.0,0000000000000000000000000000000001002867,611993,20210101.0,1028.00
16,A0E5D67D-A2E9-4401-B95E-277B562A4923,2021-04-01,75.124394,30153510,30,Won,W,41.0,0.595,1265.0,PEA1265X595SP,611993,20210401.0,1161.86
17,E1693AB6-73EB-4F3F-81E8-F5E4DF0C70B7,2021-04-01,20.807114,30211222,30,Won,W,10.0,0.450,900.0,684Z WHITE ETEX B7032,611993,20210701.0,1315.19
19,16253654-FBDA-4252-886C-55F8ACF2B08C,2021-04-01,53.581034,30329143,32,Won,S,41.0,0.550,1220.0,0000000000000000000000000000000001000113,611993,20210101.0,1002.00
20,F59B65F0-27F8-4BF2-BD25-EBA2B90869E5,2021-04-01,71.366978,30153510,30,Won,W,41.0,0.595,1265.0,GRE1265X595SP,611993,20210401.0,1161.31
21,A928C0FA-2F58-4322-A706-C4F30EDAE0F9,2021-04-01,471.838180,30202938,25,Won,W,41.0,2.500,1275.0,0000000000000000000000000000000000105003,1668701718,20210401.0,979.00
23,C2D456FC-A66A-4D95-BA1D-3CCEFF49DC2D,2021-04-01,53.729746,30329143,32,Won,S,41.0,0.550,1220.0,0000000000000000000000000000000001000063,611993,20210101.0,961.00

In [31]:
df1['status'].value_counts()

Won                74727
Lost               12920
Not lost for AM     9847
To be approved      2480
Revised             2038
Draft               1708
Offered               26
Offerable              3
Name: status, dtype: int64

In [32]:
df1['item_date'].value_counts()

2020-12-02    1720
2021-03-04    1567
2020-09-29    1346
2020-12-16    1294
2020-11-24    1196
              ...
2021-02-27       1
2020-08-01       1
2020-09-06       1
2020-12-06       1
2020-08-29       1
Name: item_date, Length: 234, dtype: int64

In [33]:
df1['application'] = df1['application'].astype(int)

In [34]:
df1['width'] = df1['width'].astype(int)

In [35]:
df1['delivery date'] = df1['delivery date'].astype(int)

In [36]:
df1['material_ref'].value_counts

<bound method IndexOpsMixin.value_counts of 0                                      DEQ1 S460MC
1         0000000000000000000000000000000000104991
2                                         S0380700
3                          DX51D+ZM310MAO 2.3X1317
4                                  2_S275JR+AR-CL1
                            ...
181668    0000000000000000000000000000000001000777
181669    0000000000000000000000000000000001000227
181670    0000000000000000000000000000000001004216
181671    0000000000000000000000000000000001001149
181672    0000000000000000000000000000000001005439
Name: material_ref, Length: 103749, dtype: object>

In [37]:
df1.drop(['material_ref'], axis=1)

,id,item_date,quantity tons,customer,country,status,item type,application,thickness,width,product_ref,delivery date,selling_price
0,EC06F063-9DF0-440C-8764-0B0C05A4F6AE,2021-04-01,54.151139,30156308,28,Won,W,10,2.00,1500,1670798778,20210701,854.00
1,4E5F4B3D-DDDF-499D-AFDE-A3227EC49425,2021-04-01,768.024839,30202938,25,Won,W,41,0.80,1210,1668701718,20210401,1047.00
2,E140FF1B-2407-4C02-A0DD-780A093B1158,2021-04-01,386.127949,30153963,30,Won,WI,28,0.38,952,628377,20210101,644.33
3,F8D507A0-9C62-4EFE-831E-33E1DA53BB50,2021-04-01,202.411065,30349574,32,Won,S,59,2.30,1317,1668701718,20210101,768.00
4,4E1C4E78-152B-430A-8094-ADD889C9D0AD,2021-04-01,785.526262,30211560,28,Won,W,10,4.00,2000,640665,20210301,577.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...
181668,DE633116-D1DF-4846-982E-55EFC3658A76,2020-07-02,102.482422,30200854,25,Won,W,41,0.96,1220,164141591,20200701,591.00
181669,A48374B1-E6DB-45F2-889A-1F9C27C099EB,2020-07-02,208.086469,30200854,25,Won,W,41,0.95,1500,164141591,20200701,589.00
181670,91643238-5C7B-4237-9A5F-63AE3D35F320,2020-07-02,4.235594,30200854,25,Won,W,41,0.71,1250,164141591,20200701,619.00
181671,7AFFD323-01D9-4E15-B80D-7D1B03498FC8,2020-07-02,-2000.000000,30200854,25,Won,W,41,0.85,1250,164141591,20200701,601.00
181672,AD0CA853-AE3C-4B2F-9FBB-8B0B965F84BC,2020-07-02,406.686538,30200854,25,Won,W,41,0.71,1240,164141591,20200701,607.00

In [38]:
df1.rename(columns={"item type": "item_type"},inplace=True)

In [39]:
df1.rename(columns={"delivery date": "delivery_date"},inplace=True)

In [40]:
df1.rename(columns={"quantity tons": "quantity_tons"},inplace=True)

In [41]:
df1['delivery_date'] = pd.to_datetime(df1['delivery_date'], format='%Y%m%d',dayfirst=True)

In [42]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103749 entries, 0 to 181672
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             103749 non-null  object
 1   item_date      103749 non-null  datetime64[ns]
 2   quantity_tons  103749 non-null  float64
 3   customer       103749 non-null  int32
 4   country        103749 non-null  int32
 5   status         103749 non-null  object
 6   item_type      103749 non-null  object
 7   application    103749 non-null  int32
 8   thickness      103749 non-null  float64
 9   width          103749 non-null  int32
 10  material_ref   103749 non-null  object
 11  product_ref    103749 non-null  int64
 12  delivery_date  103749 non-null  datetime64[ns]
 13  selling_price  103749 non-null  float64
dtypes: datetime64[ns](2), float64(3), int32(4), int64(1), object(4)
memory usage: 10.3+ MB

In [43]:
df1.drop(['material_ref'], axis=1,inplace=True)

In [44]:
df1.drop(['id'], axis=1,inplace=True)

In [45]:
df1

,item_date,quantity_tons,customer,country,status,item_type,application,thickness,width,product_ref,delivery_date,selling_price
0,2021-04-01,54.151139,30156308,28,Won,W,10,2.00,1500,1670798778,2021-07-01,854.00
1,2021-04-01,768.024839,30202938,25,Won,W,41,0.80,1210,1668701718,2021-04-01,1047.00
2,2021-04-01,386.127949,30153963,30,Won,WI,28,0.38,952,628377,2021-01-01,644.33
3,2021-04-01,202.411065,30349574,32,Won,S,59,2.30,1317,1668701718,2021-01-01,768.00
4,2021-04-01,785.526262,30211560,28,Won,W,10,4.00,2000,640665,2021-03-01,577.00
...,...,...,...,...,...,...,...,...,...,...,...,...
181668,2020-07-02,102.482422,30200854,25,Won,W,41,0.96,1220,164141591,2020-07-01,591.00
181669,2020-07-02,208.086469,30200854,25,Won,W,41,0.95,1500,164141591,2020-07-01,589.00
181670,2020-07-02,4.235594,30200854,25,Won,W,41,0.71,1250,164141591,2020-07-01,619.00
181671,2020-07-02,-2000.000000,30200854,25,Won,W,41,0.85,1250,164141591,2020-07-01,601.00
181672,2020-07-02,406.686538,30200854,25,Won,W,41,0.71,1240,164141591,2020-07-01,607.00

In [46]:
df1['selling_price'] = df1['selling_price'].astype(int)

In [47]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103749 entries, 0 to 181672
Data columns (total 12 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   item_date      103749 non-null  datetime64[ns]
 1   quantity_tons  103749 non-null  float64
 2   customer       103749 non-null  int32
 3   country        103749 non-null  int32
 4   status         103749 non-null  object
 5   item_type      103749 non-null  object
 6   application    103749 non-null  int32
 7   thickness      103749 non-null  float64
 8   width          103749 non-null  int32
 9   product_ref    103749 non-null  int64
 10  delivery_date  103749 non-null  datetime64[ns]
 11  selling_price  103749 non-null  int32
dtypes: datetime64[ns](2), float64(2), int32(5), int64(1), object(2)
memory usage: 8.3+ MB

In [350]:
df3.describe()

,customer,country,application,width,product_ref,selling_price,status_Draft,status_Lost,status_Not lost for AM,status_Offerable,status_Offered,status_Revised,status_To be approved,status_Won,item_type_IPL,item_type_Others,item_type_PL,item_type_S,item_type_W,item_type_WI
count,1.037490e+05,103749.000000,103749.000000,103749.000000,1.037490e+05,1.037490e+05,103749.000000,103749.000000,103749.000000,103749.000000,103749.000000,103749.000000,103749.000000,103749.000000,103749.00000,103749.000000,103749.000000,103749.000000,103749.000000,103749.000000
mean,3.022640e+07,44.063731,27.109244,1281.028183,4.290771e+08,1.773615e+03,0.016463,0.124531,0.094912,0.000029,0.000251,0.019644,0.023904,0.720267,0.00026,0.005793,0.044338,0.302499,0.642435,0.004675
std,6.730085e+04,24.150337,18.034063,262.630742,6.943965e+08,3.104625e+05,0.127248,0.330188,0.293094,0.005377,0.015829,0.138773,0.152750,0.448870,0.01613,0.075890,0.205845,0.459342,0.479285,0.068212
min,3.014762e+07,25.000000,2.000000,20.000000,6.117280e+05,-1.160000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.016599e+07,26.000000,10.000000,1165.000000,6.119930e+05,6.650000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.020292e+07,28.000000,20.000000,1250.000000,6.406650e+05,8.050000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,3.026890e+07,78.000000,41.000000,1500.000000,1.641416e+08,9.400000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,1.000000,1.000000,0.000000
max,3.040817e+07,113.000000,99.000000,2990.000000,1.722208e+09,1.000010e+08,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000

In [349]:
df1.head()

,item_date,quantity_tons,customer,country,status,item_type,application,thickness,width,product_ref,delivery_date,selling_price
0,2021-04-01,54.151139,30156308,28,Won,W,10,2.00,1500,1670798778,2021-07-01,854
1,2021-04-01,768.024839,30202938,25,Won,W,41,0.80,1210,1668701718,2021-04-01,1047
2,2021-04-01,386.127949,30153963,30,Won,WI,28,0.38,952,628377,2021-01-01,644
3,2021-04-01,202.411065,30349574,32,Won,S,59,2.30,1317,1668701718,2021-01-01,768
4,2021-04-01,785.526262,30211560,28,Won,W,10,4.00,2000,640665,2021-03-01,577

In [351]:
#featurescaling
from sklearn.preprocessing import StandardScaler, MinMaxScaler
import pandas as pd


# Extract the features to be scaled
X = df3[["customer","product_ref","quantity_tons"]]

# Standardization
scaler = StandardScaler()
X_std = scaler.fit_transform(X)

# Normalization
scaler = MinMaxScaler()
X_norm = scaler.fit_transform(X)

In [352]:
df3.describe()

,customer,country,application,width,product_ref,selling_price,status_Draft,status_Lost,status_Not lost for AM,status_Offerable,status_Offered,status_Revised,status_To be approved,status_Won,item_type_IPL,item_type_Others,item_type_PL,item_type_S,item_type_W,item_type_WI
count,1.037490e+05,103749.000000,103749.000000,103749.000000,1.037490e+05,1.037490e+05,103749.000000,103749.000000,103749.000000,103749.000000,103749.000000,103749.000000,103749.000000,103749.000000,103749.00000,103749.000000,103749.000000,103749.000000,103749.000000,103749.000000
mean,3.022640e+07,44.063731,27.109244,1281.028183,4.290771e+08,1.773615e+03,0.016463,0.124531,0.094912,0.000029,0.000251,0.019644,0.023904,0.720267,0.00026,0.005793,0.044338,0.302499,0.642435,0.004675
std,6.730085e+04,24.150337,18.034063,262.630742,6.943965e+08,3.104625e+05,0.127248,0.330188,0.293094,0.005377,0.015829,0.138773,0.152750,0.448870,0.01613,0.075890,0.205845,0.459342,0.479285,0.068212
min,3.014762e+07,25.000000,2.000000,20.000000,6.117280e+05,-1.160000e+03,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.016599e+07,26.000000,10.000000,1165.000000,6.119930e+05,6.650000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,3.020292e+07,28.000000,20.000000,1250.000000,6.406650e+05,8.050000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,0.000000,1.000000,0.000000
75%,3.026890e+07,78.000000,41.000000,1500.000000,1.641416e+08,9.400000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.00000,0.000000,0.000000,1.000000,1.000000,0.000000
max,3.040817e+07,113.000000,99.000000,2990.000000,1.722208e+09,1.000010e+08,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000

In [353]:
from sklearn.model_selection import train_test_split

In [354]:
from sklearn.compose import ColumnTransformer

In [355]:
from sklearn.preprocessing import OneHotEncoder

In [464]:
from sklearn.linear_model import Ridge

In [465]:
# Add Ridge regularization
ridge = Ridge(alpha=0.1)
ridge.fit(X_train, y_train)

Ridge(alpha=0.1)

In [469]:
df3.head()

,item_date,quantity_tons,customer,country,application,thickness,width,product_ref,delivery_date,selling_price,...,status_Offered,status_Revised,status_To be approved,status_Won,item_type_IPL,item_type_Others,item_type_PL,item_type_S,item_type_W,item_type_WI
0,2021-04-01,54.15113861692779,30156308,28,10,2.0,1500,1670798778,2021-07-01,854,...,0,0,0,1,0,0,0,0,1,0
1,2021-04-01,768.0248392021871,30202938,25,41,0.8,1210,1668701718,2021-04-01,1047,...,0,0,0,1,0,0,0,0,1,0
2,2021-04-01,386.1279489091378,30153963,30,28,0.38,952,628377,2021-01-01,644,...,0,0,0,1,0,0,0,0,0,1
3,2021-04-01,202.41106540948442,30349574,32,59,2.3,1317,1668701718,2021-01-01,768,...,0,0,0,1,0,0,0,1,0,0
4,2021-04-01,785.5262615733325,30211560,28,10,4.0,2000,640665,2021-03-01,577,...,0,0,0,1,0,0,0,0,1,0

In [600]:
X=df3.drop(['item_date','delivery_date','selling_price','product_ref'],axis=1)
Y=df3['selling_price']

In [585]:
X_train, X_test, y_train, y_test = train_test_split(X,Y, test_size=0.1,random_state=1)

In [586]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 93374 entries, 164185 to 172004
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer                93374 non-null  int32
 1   country                 93374 non-null  int32
 2   application             93374 non-null  int32
 3   thickness               93374 non-null  object
 4   width                   93374 non-null  int32
 5   status_Draft            93374 non-null  uint8
 6   status_Lost             93374 non-null  uint8
 7   status_Not lost for AM  93374 non-null  uint8
 8   status_Offerable        93374 non-null  uint8
 9   status_Offered          93374 non-null  uint8
 10  status_Revised          93374 non-null  uint8
 11  status_To be approved   93374 non-null  uint8
 12  status_Won              93374 non-null  uint8
 13  item_type_IPL           93374 non-null  uint8
 14  item_type_Others        93374 non-null  uint8
 15  item_type_PL            93374 non-null  uint8
 16  item_type_S             93374 non-null  uint8
 17  item_type_W             93374 non-null  uint8
 18  item_type_WI            93374 non-null  uint8
dtypes: int32(4), object(1), uint8(14)
memory usage: 4.1+ MB

In [587]:
y_train

164185    503
163406    586
147556    842
29479     857
97615     700
         ...
87725     741
171077    481
9833      831
136525    875
172004    795
Name: selling_price, Length: 93374, dtype: int32

In [588]:
X_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 10375 entries, 45706 to 168460
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   customer                10375 non-null  int32
 1   country                 10375 non-null  int32
 2   application             10375 non-null  int32
 3   thickness               10375 non-null  object
 4   width                   10375 non-null  int32
 5   status_Draft            10375 non-null  uint8
 6   status_Lost             10375 non-null  uint8
 7   status_Not lost for AM  10375 non-null  uint8
 8   status_Offerable        10375 non-null  uint8
 9   status_Offered          10375 non-null  uint8
 10  status_Revised          10375 non-null  uint8
 11  status_To be approved   10375 non-null  uint8
 12  status_Won              10375 non-null  uint8
 13  item_type_IPL           10375 non-null  uint8
 14  item_type_Others        10375 non-null  uint8
 15  item_type_PL            10375 non-null  uint8
 16  item_type_S             10375 non-null  uint8
 17  item_type_W             10375 non-null  uint8
 18  item_type_WI            10375 non-null  uint8
dtypes: int32(4), object(1), uint8(14)
memory usage: 466.1+ KB

In [589]:
y_test

45706      749
50787      725
102628     737
74462      818
134301    1091
          ...
151947     858
155568     706
78659      982
20533      959
168460     733
Name: selling_price, Length: 10375, dtype: int32

In [590]:
lr=LinearRegression()

In [591]:
lr.fit(X_train,y_train)

LinearRegression()

In [592]:
#prediction on traning data prediction
training_data=lr.predict(X_train)

In [593]:
training_data

array([10263.37789451, 24136.76850815, 10498.51389155, ...,
        -301.90378902, 10153.80517485, -1486.44529844])

In [594]:
#R score 
error_score=metrics.r2_score(y_train,training_data)

In [595]:
error_score

0.00034198144649000284

In [596]:
test_data=lr.predict(X_test)

In [597]:
test_data

array([  634.1661661 , 23963.87082132,   846.35534061, ...,
        1208.32493038,   102.92619647, 10676.5016945 ])

In [598]:
error_score1=metrics.r2_score(y_test,test_data)

In [599]:
error_score1

-673.3361726460014

In [571]:
from sklearn.linear_model import Lasso
from sklearn import metrics

In [572]:
#lasso
lasso=Lasso()

In [573]:
lasso.fit(X_train,y_train)

Lasso()

In [574]:
training_data1=lasso.predict(X_train)

In [575]:
training_data1

array([10259.92070697, 24113.47954212, 10495.05284241, ...,
        -296.65902815, 10147.22894565, -1475.37598628])

In [576]:
#R score 
error_score=metrics.r2_score(y_train,training_data1)

In [577]:
error_score

0.0003419865663916166

In [578]:
test_data1=lasso.predict(X_test)

In [579]:
error_scoree=metrics.r2_score(y_test,test_data1)

In [580]:
error_scoree

-671.8981428858463

In [581]:
import re

input_string = 'Not lost for AM'

if re.match(r'^-?\d+(?:\.\d+)?$', input_string):
    float_value = float(input_string)
else:
    # handle the error, such as setting the value to zero
    float_value = 0.0

In [582]:
try:
    float_value = float('Not lost for AM' )
except ValueError:
    # handle the error, such as setting the value to zero
    float_value = 0.0

In [583]:
input_string = "Not lost for AM"
try:
    float_value = float(input_string)
except ValueError:
    print("Unable to convert input string to float:", input_string)
    float_value = None

Unable to convert input string to float: Not lost for AM

In [ ]:
#ohe=OneHotEncoder(drop='first',sparse=False)
#status_item=ohe.fit_transform(X_train[['status','item_type']])

In [ ]:
#status_item=ohe.fit_transform(X_test[['status','item_type']])

In [ ]:
#df2=pd.DataFrame(status_item)

In [51]:
df3 = pd.concat([df1, pd.get_dummies(df1[["status","item_type"]])], axis=1)

In [52]:
df3.isnull().sum()

item_date                 0
quantity_tons             0
customer                  0
country                   0
status                    0
item_type                 0
application               0
thickness                 0
width                     0
product_ref               0
delivery_date             0
selling_price             0
status_Draft              0
status_Lost               0
status_Not lost for AM    0
status_Offerable          0
status_Offered            0
status_Revised            0
status_To be approved     0
status_Won                0
item_type_IPL             0
item_type_Others          0
item_type_PL              0
item_type_S               0
item_type_W               0
item_type_WI              0
dtype: int64

In [53]:
df3.tail(60)

,item_date,quantity_tons,customer,country,status,item_type,application,thickness,width,product_ref,...,status_Offered,status_Revised,status_To be approved,status_Won,item_type_IPL,item_type_Others,item_type_PL,item_type_S,item_type_W,item_type_WI
181560,2020-07-02,6.133762,30200854,25,Won,W,41,0.55,1000,611993,...,0,0,0,1,0,0,0,0,1,0
181561,2020-07-02,19.055390,30201866,32,Won,W,41,0.50,996,611993,...,0,0,0,1,0,0,0,0,1,0
181562,2020-07-02,8.056298,30200854,25,Won,W,41,0.68,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181563,2020-07-02,10.125819,30201866,32,Won,W,41,0.50,996,611993,...,0,0,0,1,0,0,0,0,1,0
181564,2020-07-02,8.245869,30200854,25,Won,W,41,0.37,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181565,2020-07-02,17.254009,30201866,32,Won,W,41,0.58,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181566,2020-07-02,8.020610,30200854,25,Won,W,41,0.45,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181567,2020-07-02,10.980398,30201866,32,Won,W,41,0.58,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181568,2020-07-02,5.862336,30200854,25,Won,W,41,0.55,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181569,2020-07-02,14.247148,30201866,32,Won,W,41,0.58,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181570,2020-07-02,23.883504,30200854,25,Won,W,41,0.45,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181571,2020-07-02,17.748421,30201866,32,Won,W,41,0.50,1250,611993,...,0,0,0,1,0,0,0,0,1,0
181572,2020-07-02,7.445263,30200854,25,Won,W,41,0.48,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181573,2020-07-02,16.692213,30201866,32,Won,W,41,0.50,1250,611993,...,0,0,0,1,0,0,0,0,1,0
181574,2020-07-02,7.036692,30200854,25,Won,W,41,0.58,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181575,2020-07-02,13.728952,30201866,32,Won,W,41,0.50,996,611993,...,0,0,0,1,0,0,0,0,1,0
181576,2020-07-02,2.092645,30200854,25,Won,W,41,0.55,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181577,2020-07-02,7.781863,30200854,25,Won,W,41,0.45,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181578,2020-07-02,8.595513,30200854,25,Won,W,41,0.58,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181579,2020-07-02,8.058134,30200854,25,Won,W,41,0.58,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181580,2020-07-02,9.240561,30200854,25,Won,W,41,0.58,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181581,2020-07-02,5.649627,30200854,25,Won,W,41,0.55,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181582,2020-07-02,5.879039,30200854,25,Won,W,41,0.48,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181583,2020-07-02,0.097044,30200854,25,Won,W,41,0.55,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181584,2020-07-02,9.226658,30200854,25,Won,W,41,0.55,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181585,2020-07-02,7.953504,30200854,25,Won,W,41,0.55,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181586,2020-07-02,6.526630,30200854,25,Won,W,41,0.37,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181587,2020-07-02,1.037403,30200854,25,Won,W,41,0.55,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181588,2020-07-02,9.627688,30200854,25,Won,W,41,0.68,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181589,2020-07-02,1.418609,30200854,25,Won,W,41,0.55,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181590,2020-07-02,8.307871,30200854,25,Won,W,41,0.55,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181591,2020-07-02,8.366918,30200854,25,Won,W,41,0.68,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181592,2020-07-02,0.986254,30200854,25,Won,W,41,0.55,1240,611993,...,0,0,0,1,0,0,0,0,1,0
181593,2020-07-02,2.850281,30200854,25,Won,W,41,0.68,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181594,2020-07-02,131.890774,30200854,25,Won,W,41,0.68,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181595,2020-07-02,56.502970,30200854,25,Won,W,41,0.55,1220,611993,...,0,0,0,1,0,0,0,0,1,0
181598,2020-07-02,1.457008,30198682,26,Not lost for AM,S,41,5.00,1060,164141591,...,0,0,0,0,0,0,0,1,0,0
181599,2020-07-02,7.778913,30267349,84,Revised,W,10,2.00,1000,164141591,...,0,1,0,0,0,0,0,0,1,0
181600,2020-07-02,3.553529,30267349,84,Revised,W,10,2.00,1250,164141591,...,0,1,0,0,0,0,0,0,1,0
181601,2020-07-02,3.739726,30267349,84,Revised,W,10,2.00,1500,164141591,...,0,1,0,0,0,0,0,0,1,0
181602,2020-07-02,20.155119,30267349,84,Revised,W,10,2.00,1500,164141591,...,0,1,0,0,0,0,0,0,1,0
181603,2020-07-02,15.742266,30267349,84,Revised,W,10,2.00,1000,164141591,...,0,1,0,0,0,0,0,0,1,0
181604,2020-07-02,16.391009,30267349,84,Revised,W,10,2.00,1250,164141591,...,0,1,0,0,0,0,0,0,1,0
181605,2020-07-02,34.426799,30201369,25,Won,S,41,0.60,1288,611993,...,0,0,0,1,0,0,0,1,0,0
181657,2020-07-02,3.209977,30196884,84,Won,W,10,1.00,1500,1668701376,...,0,0,0,1,0,0,0,0,1,0
181658,2020-07-02,509.314916,30200854,25,Won,W,41,0.71,1220,164141591,...,0,0,0,1,0,0,0,0,1,0
181659,2020-07-02,707.279961,30200854,25,Won,W,41,0.71,1500,164141591,...,0,0,0,1,0,0,0,0,1,0
181660,2020-07-02,704.749162,30200854,25,Won,W,41,0.84,1500,164141591,...,0,0,0,1,0,0,0,0,1,0
181661,2020-07-02,-18.000000,30200854,25,Won,W,41,0.84,1220,164141591,...,0,0,0,1,0,0,0,0,1,0
181662,2020-07-02,76.859457,30200854,25,Won,W,41,1.18,1500,164141591,...,0,0,0,1,0,0,0,0,1,0
181663,2020-07-02,1203.157826,30200854,25,Won,W,41,0.72,1240,164141591,...,0,0,0,1,0,0,0,0,1,0
181664,2020-07-02,603.114940,30200854,25,Won,W,41,0.85,1240,164141591,...,0,0,0,1,0,0,0,0,1,0
181665,2020-07-02,6.169226,30200854,25,Won,W,41,0.71,1300,164141591,...,0,0,0,1,0,0,0,0,1,0
181666,2020-07-02,82.123794,30200854,25,Won,W,41,1.18,1220,164141591,...,0,0,0,1,0,0,0,0,1,0
181667,2020-07-02,106.783299,30200854,25,Won,W,41,0.96,1240,164141591,...,0,0,0,1,0,0,0,0,1,0
181668,2020-07-02,102.482422,30200854,25,Won,W,41,0.96,1220,164141591,...,0,0,0,1,0,0,0,0,1,0
181669,2020-07-02,208.086469,30200854,25,Won,W,41,0.95,1500,164141591,...,0,0,0,1,0,0,0,0,1,0
181670,2020-07-02,4.235594,30200854,25,Won,W,41,0.71,1250,164141591,...,0,0,0,1,0,0,0,0,1,0
181671,2020-07-02,-2000.000000,30200854,25,Won,W,41,0.85,1250,164141591,...,0,0,0,1,0,0,0,0,1,0
181672,2020-07-02,406.686538,30200854,25,Won,W,41,0.71,1240,164141591,...,0,0,0,1,0,0,0,0,1,0

In [54]:
df1.isnull().sum()

item_date        0
quantity_tons    0
customer         0
country          0
status           0
item_type        0
application      0
thickness        0
width            0
product_ref      0
delivery_date    0
selling_price    0
dtype: int64

In [82]:
df3['status'].value_counts()

Won                74727
Lost               12920
Not lost for AM     9847
To be approved      2480
Revised             2038
Draft               1708
Offered               26
Offerable              3
Name: status, dtype: int64

In [56]:
from sklearn.linear_model import LinearRegression

from sklearn import metrics

In [57]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 103749 entries, 0 to 181672
Data columns (total 26 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   item_date               103749 non-null  datetime64[ns]
 1   quantity_tons           103749 non-null  float64
 2   customer                103749 non-null  int32
 3   country                 103749 non-null  int32
 4   status                  103749 non-null  object
 5   item_type               103749 non-null  object
 6   application             103749 non-null  int32
 7   thickness               103749 non-null  float64
 8   width                   103749 non-null  int32
 9   product_ref             103749 non-null  int64
 10  delivery_date           103749 non-null  datetime64[ns]
 11  selling_price           103749 non-null  int32
 12  status_Draft            103749 non-null  uint8
 13  status_Lost             103749 non-null  uint8
 14  status_Not lost for AM  103749 non-null  uint8
 15  status_Offerable        103749 non-null  uint8
 16  status_Offered          103749 non-null  uint8
 17  status_Revised          103749 non-null  uint8
 18  status_To be approved   103749 non-null  uint8
 19  status_Won              103749 non-null  uint8
 20  item_type_IPL           103749 non-null  uint8
 21  item_type_Others        103749 non-null  uint8
 22  item_type_PL            103749 non-null  uint8
 23  item_type_S             103749 non-null  uint8
 24  item_type_W             103749 non-null  uint8
 25  item_type_WI            103749 non-null  uint8
dtypes: datetime64[ns](2), float64(2), int32(5), int64(1), object(2), uint8(14)
memory usage: 9.7+ MB

In [58]:
df3['thickness']=df3['thickness'].astype(str)

In [59]:
df3['quantity_tons']=df3['quantity_tons'].astype(str)

In [60]:
df3.rename({'quantity tons': 'quantity_tons'}, axis=1, inplace=True)

In [ ]:
df3.head(60)

In [ ]:
df3['delivery_date'] = pd.to_datetime(df3['delivery_date']).dt.date

In [ ]:
df3['item_date'] = pd.to_datetime(df3['item_date']).dt.date

In [ ]:
df3['delivery_date'] = pd.to_datetime(df3['delivery_date'])

In [ ]:
df3['item_date'] = pd.to_datetime(df3['item_date'])

In [ ]:
df3.info()

In [ ]:
df3.head()

In [ ]:
df3.info()